#!/usr/bin/env ruby

require_relative '../cmd_line_helper'

END {
  part1_fun = ->(input_path) { part1(input_path) }
  part2_fun = ->(input_path) { part2(input_path) }
  run part1_fun, part2_fun
}

def part1(input_path)
  puts "Part 1 for file: #{input_path}"
  input = File.read(input_path)
  matches = input.scan(/mul\((\d*),(\d*)\)/)
  res = matches.map { |l, r| l.to_i * r.to_i }.sum
  puts "Answer Part 1: #{res}"
end

def part2(input_path)
  puts "Part 2 for file: #{input_path}"
  input = File.read(input_path)
  input += "do()"
  input_without_donts = input.gsub! /don't\(\)[\s\S]*?do\(\)/, '_'
  matches = input_without_donts.scan(/mul\((\d*),(\d*)\)/)
  res = matches.map { |l, r| l.to_i * r.to_i }.sum
  puts "Answer Part 2: #{res}"
end
