#!/usr/bin/env ruby

require_relative '../cmd_line_helper'

END {
  part1_fun = ->(input_path) { part1(input_path) }
  part2_fun = ->(input_path) { part2(input_path) }
  run part1_fun, part2_fun
}

def part1(input_path)
  puts "Part 1 for file: #{input_path}"
  input = File.read(input_path)
  stones = input.strip.split(' ').map(&:to_i)
  25.times { stones = blink(stones) }
  res = stones.size
  puts "Answer Part 1: #{res}"
end

def blink(stones)
  new_stones = []
  stones.reverse.each do |stone|
    if stone == 0
      new_stones.unshift(1)
    else
      stone_string = stone.to_s
      if stone_string.size.even?
        left = stone_string.slice(0, stone_string.size / 2).to_i
        right = stone_string.slice(stone_string.size / 2, stone_string.size).to_i
        new_stones.unshift(right)
        new_stones.unshift(left)
      else
        new_stones.unshift stone * 2024
      end
    end
  end
  new_stones
end

def part2(input_path)
  puts "Part 2 for file: #{input_path}"
  input = File.read(input_path)
  stones_count = input.strip.split(' ').map(&:to_i).tally
  75.times { stones_count = blink_count(stones_count) }
  res = stones_count.values.sum
  puts "Answer Part 2: #{res}"
end

def blink_count(stones_count)
  next_count = {}
  stones_count.each do |stone, count|
    if stone == 0
      next_count[1] = (next_count[1] || 0) + count
    else
      stone_string = stone.to_s
      if stone_string.size.even?
        left = stone_string.slice(0, stone_string.size / 2).to_i
        right = stone_string.slice(stone_string.size / 2, stone_string.size).to_i
        if left == right
          next_count[left] = (next_count[left] || 0) + (2 * count)
        else
          next_count[left] = (next_count[left] || 0) + count
          next_count[right] = (next_count[right] || 0) + count
        end
      else
        new_stone_value = stone * 2024
        next_count[new_stone_value] = (next_count[new_stone_value] || 0) + count
      end
    end
  end
  next_count
end
