#!/usr/bin/env ruby

require_relative '../cmd_line_helper'

END {
  part1_fun = ->(input_path) { part1(input_path) }
  part2_fun = ->(input_path) { part2(input_path) }
  run part1_fun, part2_fun
}

def part1(input_path)
  puts "Part 1 for file: #{input_path}"
  input = File.read(input_path)
  s = input.split("\n\n")
  register_init_lines = s[0].split("\n")
  init_a = register_init_lines[0].match(/Register A: (\d+)/)[1].to_i
  init_b = register_init_lines[1].match(/Register B: (\d+)/)[1].to_i
  init_c = register_init_lines[2].match(/Register C: (\d+)/)[1].to_i
  program = s[1].split(": ")[1].split(',').map(&:to_i)
  registers = [init_a, init_b, init_c]
  machine = { registers: registers, program: program, pointer: 0 }
  out = execute_program(machine)
  res = out.join ','
  puts "Answer Part 1: #{res}"
end

def execute_program(machine)
  program = machine[:program]
  pointer = machine[:pointer]
  out = []

  while pointer < machine[:program].length
    # p "registers: #{machine[:registers]} pointer: #{pointer}"
    instruction = program[pointer]
    operand = program[pointer + 1]
    case instruction
    when 0
      c_operand = combo_operand machine, operand
      numerator = machine[:registers][0]
      result = numerator / 2 ** c_operand
      # p "adv: #{numerator} / 2**#{c_operand} result: #{result}"
      machine[:registers][0] = result
    when 1
      result = machine[:registers][1] ^ operand
      # p "bxl: #{machine[:registers][1]} ^ #{operand} result: #{result}"
      machine[:registers][1] = result
    when 2
      c_operand = combo_operand machine, operand
      result = c_operand % 8
      # p "bst: #{c_operand} % 8 result: #{result}"
      machine[:registers][1] = result
    when 3
      # p "jnz: #{machine[:registers][0]} != 0"
      if machine[:registers][0] != 0
        pointer = operand
        next
      end
    when 4
      result = machine[:registers][1] ^ machine[:registers][2]
      # p "bxc: #{machine[:registers][1]} ^ #{machine[:registers][2]} result: #{result}"
      machine[:registers][1] = result
    when 5
      c_operand = combo_operand machine, operand
      result = c_operand % 8
      # p "out: #{c_operand} % 8 result: #{result}"
      out << result
    when 6
      c_operand = combo_operand machine, operand
      numerator = machine[:registers][0]
      result = numerator / 2 ** c_operand
      # p "bdv: #{numerator} / 2**#{c_operand} result: #{result}"
      machine[:registers][1] = result
    when 7
      c_operand = combo_operand machine, operand
      numerator = machine[:registers][0]
      result = numerator / 2 ** c_operand
      # p "cdv: #{numerator} / 2**#{c_operand} result: #{result}"
      machine[:registers][2] = result
    end
    pointer += 2
  end
  out
end

def combo_operand(machine, operand)
  case operand
  when 0, 1, 2, 3
    operand
  when 4
    machine[:registers][0]
  when 5
    machine[:registers][1]
  when 6
    machine[:registers][2]
  when 7
    raise NotImplementedError
  else
    raise NotImplementedError
  end
end

def part2(input_path)
  puts "Part 2 for file: #{input_path}"
  input = File.read(input_path)
  s = input.split("\n\n")
  register_init_lines = s[0].split("\n")
  init_a = register_init_lines[0].match(/Register A: (\d+)/)[1].to_i
  init_b = register_init_lines[1].match(/Register B: (\d+)/)[1].to_i
  init_c = register_init_lines[2].match(/Register C: (\d+)/)[1].to_i
  program = s[1].split(": ")[1].split(',').map(&:to_i)
  # between 2**45 and 2**48 - 1 => 35_184_372_088_832 and 281_474_976_710_655
  # we have an output of 16
  # A = 2 => [0]
  # A = 16 => [2, 0] to A = 23 => [6, 0]
  # A = 128 => [0, 2, 0] to A = 191 => [2, 6, 0]
  # A = 1024 => [2, 0, 2, 0] to A = 1535 => [2, 2, 6, 0]
  # A = 8192 => [2, 2, 0, 2, 0] to A = 12287 => [2, 2, 2, 6, 0]

  # A = 2 => [0]
  # A = 17 => [3, 0]
  # A = 165 => [3, 3, 0]
  # A = 1323 => [0, 3, 3, 0]
  # A = 10586 => [5, 0, 3, 3, 0]
  # A = 84690 = 0o245322 => [5, 5, 0, 3, 3, 0]
  # A = 677547 = 0o2453253 => [4, 5, 5, 0, 3, 3, 0]
  # A = 5420377 = 0o24532531 => [1, 4, 5, 5, 0, 3, 3, 0]
  init_a = 0
  while true
    # p "init_a: #{init_a}" #if init_a % 100000 == 0
    # scale a quicker by approaching the solution
    # a = init_a
    # a = 0o245 * 8**3 + init_a
    # a = 0o245325 * 8**6 + init_a
    a = 0o24532534 * 8**8 + init_a

    registers = [a, init_b, init_c]
    machine = { registers: registers, program: program.dup, pointer: 0 }
    out = execute_program(machine)
    # program: 2,4,1,6,7,5,4,6,1,4,5,5,0,3,3,0
    if out == [0] ||
      out == [3, 0] ||
      out == [3, 3, 0] ||
      out == [0, 3, 3, 0] ||
      out == [5, 0, 3, 3, 0] ||
      out == [5, 5, 0, 3, 3, 0] ||
      out == [4, 5, 5, 0, 3, 3, 0] ||
      out == [1, 4, 5, 5, 0, 3, 3, 0] ||
      out == [6, 1, 4, 5, 5, 0, 3, 3, 0] ||
      out == [4, 6, 1, 4, 5, 5, 0, 3, 3, 0] ||
      out == [5, 4, 6, 1, 4, 5, 5, 0, 3, 3, 0] ||
      out == [7, 5, 4, 6, 1, 4, 5, 5, 0, 3, 3, 0] ||
      out == [6, 7, 5, 4, 6, 1, 4, 5, 5, 0, 3, 3, 0] ||
      out == [1, 6, 7, 5, 4, 6, 1, 4, 5, 5, 0, 3, 3, 0] ||
      out == [4, 1, 6, 7, 5, 4, 6, 1, 4, 5, 5, 0, 3, 3, 0]
      p "init_a: #{init_a} a: #{a} oct: #{a.to_s 8} out: #{out} #out: #{out.size}"
    end

    if out == program
      puts "Answer Part 2: #{a}"
      break
    end
    init_a += 1
  end
end
