#!/usr/bin/env ruby

require_relative '../cmd_line_helper'

END {
  part1_fun = ->(input_path) { part1(input_path) }
  part2_fun = ->(input_path) { part2(input_path) }
  run part1_fun, part2_fun
}

def part1(input_path)
  puts "Part 1 for file: #{input_path}"
  input = File.read(input_path)
  left, right = get_left_and_right(input)
  left.sort!
  right.sort!
  res = left.zip(right).map { |zipped| (zipped[0] - zipped[1]).abs }.sum
  puts "Answer Part 1: #{res}"
end

def part2(input_path)
  puts "Part 2 for file: #{input_path}"
  input = File.read(input_path)
  left, right = get_left_and_right(input)
  right_tally = right.tally
  res = left.map { |l| l * (right_tally[l] || 0) }.sum
  puts "Answer Part 2: #{res}"
end

def get_left_and_right(input)
  left = []
  right = []
  input.split("\n")
       .each { |line|
         split = line.split('   ').map(&:to_i)
         left << split[0]
         right << split[1]
       }
  [ left, right ]
end
